# Generated by Django 5.2.6 on 2025-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Периодичность выполнения привычки для напоминания в днях",
                verbose_name="Периодичность",
            ),
        ),
    ]
